config/routes.rb
Rails.application.routes.draw do
  get 'reservations/new'
  get 'reservations/create'
  devise_for :users, :controllers => { :registrations => 'user_manuals' }
  
  root to: 'pets#home'

  resources :shelters, only: [:show, :new, :create] do
    resources :pets, only: [:new, :create]
  end

  resources :pets, except: [:new, :create] do
    resources :reservations, only: [:new, :create]
  end
  
  resources :reservations, only: [:index] do
    resources :pet_reviews, only: [:new, :create]
    resources :shelter_reviews, only: [:new, :create]
  end



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :shelter

  has_many :pet_reviews, dependent: :destroy
  has_many :reservations, dependent: :destroy
  has_one_attached :photo

  validates :name, presence: true
  validates :age, presence: true
  validates :animal_type, presence: true
  validates :price_per_day, presence: true
  validates :gender, presence: true
  validates :breed, presence: true
  validates :description, presence: true

  def self.search(search)
    if search 
      joins(shelter: :user).where("lower(users.city) LIKE ?", "%#{search.downcase}%")
    else 
      all
    end 
  end 
 
end 

app/models/pet_review.rb
class PetReview < ApplicationRecord
  belongs_to :pet
  belongs_to :user
  validates :rating, inclusion: { in: 0..5, message: 'must be a number between 1-5'} 
  validates :content, presence: true
  has_many_attached :photos
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :pet

  validates :start_date, :end_date, presence: true
  validate :end_date_after_start_date

  def end_date_after_start_date
    

    if end_date < start_date
      errors.add(:end_date, "must be after the start date")
    end
 end
end

app/models/shelter.rb
class Shelter < ApplicationRecord
  belongs_to :user
  has_many :pets, dependent: :destroy
  has_many :shelter_reviews, dependent: :destroy
  
  has_one_attached :photo

  validates :name, presence: true
  
end

app/models/shelter_review.rb
class ShelterReview < ApplicationRecord
  belongs_to :shelter
  belongs_to :user

  validates :rating, inclusion: { in: 0..5, message: 'must be a number between 1-5'} 
  validates :content, presence: true
  has_many_attached :photos
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  CATEGORIES = ['Caretaker', 'Shelter']

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :shelter, dependent: :destroy
  has_many :pets, through: :shelter, dependent: :destroy

  has_one_attached :photo

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :birth_date, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :zip_code, presence: true
  validates :user_type, acceptance: { accept: CATEGORIES }, presence: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :user_type, :address, :city, :zip_code, :birth_date, :photo, :shelter_name])
  end
end

app/controllers/pet_reviews_controller.rb
class PetReviewsController < ApplicationController

  def new
    # @pet = Pet.find(params[:pet_id])
    @reservation = Reservation.find(params[:reservation_id])
    @pet_review = PetReview.new
  end

  def create
    @pet_review = PetReview.new(pet_review_params)
    @reservation = Reservation.find(params[:reservation_id])
    @pet = @reservation.pet
    @user = current_user
    @pet_review.pet = @pet
    @pet_review.user = @user
    if @pet_review.save
      redirect_to pet_path(@pet)
    else
      render :new
    end
  end

  private
  
  def pet_review_params
    params.require(:pet_review).permit(:rating, :content, :pet_id)
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  def home  
  end

  def index
    @pets = Pet.search(params[:search])

  end

  def show
    @pet = Pet.find(params[:id])
  end

  def new
    @pet = Pet.new
    @shelter = Shelter.find(params[:shelter_id])
  end

  def create
    @pet = Pet.new(pet_params)
    @shelter = Shelter.find(params[:shelter_id])
    @pet.shelter = @shelter
    @pet.save

    redirect_to shelter_path(@shelter)
  end

  def edit
    @pet = Pet.find(params[:id])
  end

  def update
    @pet = Pet.find(params[:id])
    @pet.update(pet_params)

    redirect_to shelter_path(@pet.shelter_id)
  end

  def destroy
    @pet = Pet.find(params[:id])
    @pet.destroy

    redirect_to pet_path
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :age, :animal_type, :price_per_day, :gender, :breed, :description, :photo)
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
    @reservations = Reservation.where(user_id: current_user)
  end
  
  def new
    @user = current_user
    if @user 
    @reservation = Reservation.new
    @pet = Pet.find(params[:pet_id])
    else
      redirect_to user_session_path
    end
  
    

  end

  def create
    @reservation = Reservation.new(reservation_params)
    @pet = Pet.find(params[:pet_id])
    @user = current_user
    @reservation.pet = @pet
    @reservation.user = @user
    if @reservation.save
      redirect_to reservations_path, notice: "Reservation successful! Your friend is waiting for you!"
    else
      render :new
    end
  end

  private

  def reservation_params
    params.require(:reservation).permit(:total_price, :start_date, :end_date)
  end
end

app/controllers/shelter_reviews_controller.rb
class ShelterReviewsController < ApplicationController
  
  def new
    @reservation = Reservation.find(params[:reservation_id])
    @shelter_review = ShelterReview.new
  end

  def create
    @shelter_review = ShelterReview.new(shelter_review_params)
    @reservation = Reservation.find(params[:reservation_id])
    
    @shelter = @reservation.pet.shelter
    
    @user = current_user
    
    @shelter_review.shelter = @shelter
    @shelter_review.user = @user
    if @shelter_review.save
      redirect_to pet_path(@reservation.pet)
    else
      render :new
    end
  end

  private
  
  def shelter_review_params
    params.require(:shelter_review).permit(:rating, :content, :pet_id, :photos)
  end
end

app/controllers/shelters_controller.rb
class SheltersController < ApplicationController
  def new 
    @shelter = Shelter.new
  end

def create 
  @shelter = Shelter.new(shelter_params)
  @shelter.user = current_user

  if @shelter.save
    redirect_to shelter_path(@shelter)
  else 
    render :new
  end 
end

  def show
    @shelter = Shelter.find(params[:id])
    @pets = @shelter.pets
  end

  def shelter_params 
    params.require(:shelter).permit(:name)
  end 
end

app/controllers/user_manuals_controller.rb
class UserManualsController < Devise::RegistrationsController
    before_action :user_params_config, if: :devise_controller?
    def create 
        
        @user = User.create(user_params)
        sign_in(@user)
        if @user.user_type == "Shelter" && @user.save
            redirect_to new_shelter_path
        elsif !@user.save
            render :new
        else 
            redirect_to root_path
        end 
    end
    
    

    def user_params_config
        devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :user_type, :address, :city, :zip_code, :birth_date, :photo, :shelter_name, :email, :password, :password_confirmation])
    end 
    def user_params 
        params.require(:user).permit( :first_name, :last_name, :user_type, :address, :city, :zip_code, :birth_date, :photo, :shelter_name, :email, :password, :password_confirmation)
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper

  def get_photo_key(object)
    if object.photo.attachment.present?
      photo_key = object.photo.key
    else
      photo_key = "No_Image_Available_g6q72z" #no photo image on cloudinary
    end 
 end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Foster Friends</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed&display=swap" rel="stylesheet">
</head>

<body>
  <%= render 'shared/navbar' %>
  <p class="alert">
    <%= alert %>
  </p>
  <%= yield %>
</body>

</html>

app/views/pet_reviews/new.html.erb
<div class="container mt-5">
  <div class="row border border-warning justify-content-center p-5">
  <div class="col-6">
  <h2 style="text-align:center">Please leave a review</h2>
    <%= simple_form_for [@reservation, @pet_review] do |f| %>
      
      <%= f.input :rating %>
      <%= f.input :content %>
      <%= f.submit "Submit review", class: "btn btn-info rounded-pill " %>
    <% end %>
  </div>

</div>

app/views/pets/edit.html.erb
<h1 class="text-center mb-4 mt-4 mr-3">  Edit <%= @pet.name %>'s information</h1> 
<div class="container form">
<%= simple_form_for @pet do |f| %>
<%= f.input :name %>
<%= f.input :description %>
<%= f.input :age %>
<%= f.input :gender %>
<%= f.input :animal_type %>
<%= f.input :breed %>
<%= f.input :price_per_day %>
<%= f.submit %>

<% end %>
</div>

app/views/pets/home.html.erb
<div class="main-div">
  <div class=container>
      <img class="logo-img" src="https://ci6.googleusercontent.com/proxy/O5Hy-WtOEzQ_1-syh0TZgI3ctyS90IsRKTyIh6oCUgELchFT93eiGXUYzuauaiXwJRlFCrZzztXfzjhVDdNy8P7vOmajDEqaixswkHFCQMMhhu27jQoYvxXDcKxvehjKNa8WpJPbWhV3296TqhQQuzxrieI1PkAw=s0-d-e1-ft#https://www.freelogodesign.org/file/app/client/thumb/cffd8def-62df-40a0-ba2e-859b661d9688_200x200.png">
        
        <% if current_user.present? && current_user.user_type == "Shelter" %>
          <div class="text-center">
            <%= link_to "Go to shelter dashboard", shelter_path(current_user.shelter), class: "btn btn-primary btn-lg btn-go-dash" %>
          </div>
        <% else %>
        <h1 class="text-center mb-5" style="font-family: 'Roboto Condensed', sans-serif;"> Find a friend in your Neighborhood!</h1>
        <div>
        <%= form_tag pets_path, :method => 'get', :class => "home-search" do  %>
            <%= submit_tag "Search", :class => "home-btn" %>
            <%= text_field_tag :search, params[:search], :class => "form-control me-2 form-search" %>
          <% end %>
        <% end %>
    </div>    
  </div>
  <img class="banner-img" src="https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fgooddogmarketing.com%2Fwp-content%2Fuploads%2F2013%2F09%2FCatsAndDogs_3000.jpg&f=1&nofb=1">

</div>

app/views/pets/index.html.erb
<p id="notice">
  <%= notice %>
</p>
<div class="container1 text-center">
<% if @pets.first == nil %>
  <h1 class="mt-4 mb-5"> No results for pets in <%= params[:search].capitalize %>
  <% else %>
    <% if params[:search] == ""  || params[:search] == nil %>
    <h1 class="mt-4 mb-5">All pets</h1>
    <% else %>
  <h1 class="mt-4 mb-5">Pets In
    <%= params[:search].capitalize %>
  </h1>
  <% end %>
  <div class="row main-holder">
    <% @pets.each do |pet| %>
    <div class="col-sm-4">
      <div class="card individual-card justify-content-around mb-5">
        <% pet_photo_key = get_photo_key(pet) %>
        
        <div>
          <%= cl_image_tag pet_photo_key, alt: "pet photo", class: "pet-img card-img-top" %>
        </div>

        <div class="card-body list-group list-group-flush d-flex flex-column align-items-center ">
          <div class="card-title mt-2">
            <p style="font-size: 2.5rem"><%= pet.name %></p>
          </div>
          <div class="card-text">
            <%= pet.description %>
          </div>
          <div class="list-group-item"><span class="bold">Age: </span>
            <%= pet.age %>
          </div>
          <div class="list-group-item">
            <span class="bold">Gender: </span><%= pet.gender %>
          </div>
          <div class="list-group-item">
          <span class="bold">Breed: </span> <%= pet.breed %>
          </div>
          <div class="list-group-item">
           <span class="bold">Shelter:  </span> <%= link_to pet.shelter.name, shelter_path(pet.shelter) %>
          </div>
          <div class="list-group-item">
          <span class="bold">Location: </span>
             <%= pet.shelter.user.city %>
          </div>
          <div class="list-group-item">
          <span class="bold">Price per day: </span>
             <%= pet.price_per_day %>
          </div>
          <div class="list-group-item mb-5">
          <%= link_to "Learn more about #{pet.name}" , pet, class: " btn btn-warning bottom-link " %>
          </div>
      </div>
      </div>

    </div>
    <% end %>
  </div>
</div>
<% end %>

app/views/pets/new.html.erb
<div class="container">
<%= link_to "Back to shelter", shelter_path(@shelter), class: "btn btn-primary mb-4 back-shelter-btn" %>
<%= simple_form_for [@shelter, @pet]  do |f| %>
  <%= f.input :name %>
  <%= f.input :age %>
  <%= f.input :animal_type %>
  <%= f.input :price_per_day %>
  <%= f.input :gender %>
  <%= f.input :breed %>
  <%= f.input :description %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>

app/views/pets/show.html.erb
<p id="notice"><%= notice %></p>
  <div class="container mt-5">
    <div class="row justify-content-center" >
      <div class="row-col-12">
        <div class="card border-info mb-3">
          <% pet_photo_key = get_photo_key(@pet) %>
          <%= cl_image_tag pet_photo_key, alt: "pet photo", class: "pet-img card-img-top"%>
            <div class="card-header fw-bold" style="font-size: 30px"><%= @pet.name %></div>
            <div class="card-body m-3">
              <h4 class="card-title text-uppercase" style="font-weight: bold">Details: </h4>
              <p class="card-text text-uppercase" style="font-weight: bold">Age: <span style="font-weight: 300"><%= @pet.age %></span> </p>
              <p class="card-text text-uppercase" style="font-weight: bold">Animal Type: <span style="font-weight: 300"><%= @pet.animal_type %></span> </span>
              <p class="card-text text-uppercase" style="font-weight: bold">Price per day: <span style="font-weight: 300"><%= @pet.price_per_day %></span> </p>
              <p class="card-text text-uppercase" style="font-weight: bold">Gender: <span style="font-weight: 300"><%= @pet.gender %></span>  </p>
              <p class="card-text text-uppercase" style="font-weight: bold">Breed: <span style="font-weight: 300"><%= @pet.breed %></span> </p>
              <p class="card-text text-uppercase" style="font-weight: bold">Description: <span style="font-weight: 300"><%= @pet.description %></span> </p>
            </div>
        </div>
        <%= link_to 'Back', pets_path, class:"btn btn-warning rounded"   %> |
        <%= link_to 'Reserve', new_pet_reservation_path(@pet), class:"btn btn-warning rounded", style: "background-color: #F56F6C" %>
      </div>
    </div>
  </div>

  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-12">
        <div class="card border-info mb-3" >
          <div class="card-header fw-bold" style="font-size: 30px">
            <h3>Reviews about <%= @pet.name %> </h3>
          </div>
          <% @pet.pet_reviews.each do |pet_review| %>
          <div class="card border-warning" style="max-width: 100rem;">
            <div class="card-header"><%= "Review from: #{pet_review.user.first_name} "  %></div>
            <div class="card-body m-3">
                <p class="card-text text-uppercase" style="font-weight: bold">Stars: 
                <%= render "shared/review_stars", {rating: pet_review.rating} %>
                </p>
                <p class="card-text text-uppercase" style="font-weight: bold">Content: <span style="font-weight: 300"><%= pet_review.content %></span> </p>
            </div>
        </div>
        <% end %>
      </div>
      
       
    </div>
   
  </div>
  

  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-12">
      <div class="card border-info mb-3">
        <div class="card-header fw-bold" style="font-size: 30px">
          <h3>Reviews about <%= @pet.shelter.name %> </h3>
        </div>
        <% @pet.shelter.shelter_reviews.each do |shelter_review| %>
        <div class="card border-warning" style="max-width: 100rem;">
          <div class="card-header"><%= "Review from: #{shelter_review.user.first_name} "  %></div>
          <div class="card-body m-3">
              <p class="card-text text-uppercase" style="font-weight: bold">Stars: 
                  
              <%= render "shared/review_stars", {rating: shelter_review.rating} %>
                
                
              <p class="card-text text-uppercase" style="font-weight: bold">Content: <span style="font-weight: 300"><%= shelter_review.content %></span> </p>
          </div>
      
    <% end %>
  </div>

app/views/reservations/index.html.erb
<div class="container m-5 " style="max-width: 100rem">
    <%= render 'shared/notices' %>
    <% if @reservations.first == nil %>
      <h1> No reservations found! </h1>
  <%= link_to "Go back to home page", root_path, class: "btn btn-primary mx-auto"  %>
  <% else %>
    <h1 class="text-center">Reservations</h1>
    <div class="row border-top-0 row-cols-3 pt-5" >
    <% @reservations.reverse.each do |reservation| %>
  
    <div class="col my-3 d-flex align-items-stretch">
      <div class="card border-warning" style="max-width: 25rem; box-shadow: rgba(0, 0, 0, 0.16) 0px 3px 6px, rgba(0, 0, 0, 0.23) 0px 3px 6px;" >
      <div class="card-header text-center">

        <% pet_photo_key = get_photo_key(reservation.pet) %>
        <%= cl_image_tag pet_photo_key, crop: :thumb, gravity: :face, class: "avatar dropdown-toggle mr-4", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>

        
       <h2 class="mt-2"> Booking of <%= reservation.pet.name %></h2>
      </div>
        
        <div class="card-body text-center m-3">
          
          <% if reservation.end_date.past? && reservation %>
            <p class="card-text text-center"> You rented <%= reservation.pet.name %> from <%= reservation.pet.shelter.name %>  from <%= reservation.start_date %> to <%= reservation.end_date %> </p>
          <% else %>
            <p class="card-title">You are booking <%= reservation.pet.name %> from <%= reservation.start_date %> to <%= reservation.end_date %></p>
            <p class="card-text">Total price is <%= reservation.total_price %></p>
            <p class="card-text"> Please return <%= reservation.pet.name %> to <%= reservation.pet.shelter.name %>  on <%= reservation.end_date %></li>
          <% end %>
          <p class="card-text" style="font-size: 2rem"> <%= reservation.pet.name %>'s information:</p>
          <ul class="list-group list-group-flush">
            <li class="list-group-item"><span class="bold">Description: </span><%= reservation.pet.description %></li>
            <li class="list-group-item"><span class="bold">Age:</span> <%= reservation.pet.age %></li>
            <li class="list-group-item"><span class="bold">Gender:</span> <%= reservation.pet.gender %></li>
            <li class="list-group-item"><span class="bold">Breed:</span> <%= reservation.pet.breed %></li>
            <li class="list-group-item"><span class="bold">Shelter:</span> <%= reservation.pet.shelter.name %></li>
            <li class="list-group-item"><span class="bold">Price Per Day:</span> <%= reservation.pet.price_per_day %></li>
            <li class="list-group-item"><span class="bold">City:</span> <%= reservation.pet.shelter.user.city %></li>
          </ul>
        </div>
        <div class="card-footer text-center">
          <small class="text-muted">
          <% if reservation.end_date.past? %>
            <%= link_to "Pet review",  new_reservation_pet_review_path(reservation), class:"btn btn-warning mr-3", style: "box-shadow: rgba(0, 0, 0, 0.16) 0px 3px 6px, rgba(0, 0, 0, 0.23) 0px 3px 6px;" %>
            <%= link_to "Shelter review",  new_reservation_shelter_review_path(reservation), class:"btn btn-warning", style: "box-shadow: rgba(0, 0, 0, 0.16) 0px 3px 6px, rgba(0, 0, 0, 0.23) 0px 3px 6px;" %>
          <% else %>
            <li class="card-text"> Please return <%= reservation.pet.name %> to <%= reservation.pet.shelter.name %>  on <%= reservation.end_date %></li>
          <% end  %>  
          </small>

        </div>
      </div>
    
    
    </div>
    
    

  <% end  %>
  <% end  %>
  </div>
</div>

app/views/reservations/new.html.erb
<div class="container">
<div class="hidden booking-pet-price" data-pet-price="<%= @pet.price_per_day %>"></div>
<%= simple_form_for [@pet, @reservation]  do |f| %>
  <%= f.input :start_date %>
  <%= f.input :end_date %>
  <%= f.hidden_field :total_price %>
  <%= f.submit %>
<% end %>

<div id="price">
  <h6 class="text-alert" style="color: rgb(242,146,36); margin-top: 20px;"></h6>
  <h3 class='displayPrice' style="margin-top: 15px;">Total: </h3>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon d-flex ">
<div class="nav-left-items d-flex collapse navbar-collapse" id="navbarSupportedContent">
  <%= link_to root_path, class: "navbar-brand" do %>
  <%= image_tag "https://ci6.googleusercontent.com/proxy/O5Hy-WtOEzQ_1-syh0TZgI3ctyS90IsRKTyIh6oCUgELchFT93eiGXUYzuauaiXwJRlFCrZzztXfzjhVDdNy8P7vOmajDEqaixswkHFCQMMhhu27jQoYvxXDcKxvehjKNa8WpJPbWhV3296TqhQQuzxrieI1PkAw=s0-d-e1-ft#https://www.freelogodesign.org/file/app/client/thumb/cffd8def-62df-40a0-ba2e-859b661d9688_200x200.png", class: "logo-nav" %>
  <% end %>
  <ul class="navbar-nav mx-auto">
   <li class="mx-auto">
        <%= link_to "Home", root_path, class: "nav-btn" %>
      </li>
      </ul>
  </div>
  <div>
  <% if user_signed_in?%>
  <div class="reservations">
  <ul class="navbar-nav">
      <li class="mx-auto">
      </li>
      </ul>
      </div>
      <% end %>
      </div>
  <div class="collapse navbar-collapse d-flex" id="navbarSupportedContent">
    <ul class="navbar-nav mx-auto">
      <% if user_signed_in? == false  %> 
      <li class="logbtn">
        <%= link_to "Login", new_user_session_path %>
      </li>
       <% end  %>
      <% if current_page?(root_path) == false  %>
      <div class="d-flex searchfld mx-auto">
        <%= form_tag pets_path, :method => 'get', :class => "d-flex" do  %>
        <%= text_field_tag :search, params[:search], :class => "form-control me-2 searchbar mt-2" %>
        <div>
          <%= submit_tag "Search", :class => "btnnav" %>
          <% end %>
          <% end %>
          <% if user_signed_in?  %>
          <li class="nav-item dropdown">
          <%user_photo = get_photo_key(current_user)%>
        <%= cl_image_tag user_photo, crop: :thumb, gravity: :face, class: "avatar dropdown-toggle mr-4", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <% if current_user.user_type == "Shelter" %>
          <% else %>
            <%= link_to "Reservations", reservations_path, class: "dropdown-item" %>
          <% end %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </li>
      <% end  %>
          
        </div>
      </li>
     
     
    </ul>
  </div>
</div>

app/views/shared/_notices.html.erb
<% if notice %>
  <div class="alert alert-warning alert-dismissible fade show text-center" role="alert">
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-danger alert-dismissible fade show text-center" role="alert">
    <%= alert %>
  </div>
<% end %>

app/views/shared/_review_stars.html.erb
<% 5.times do  |idx|   %>
  <% if rating >= (idx + 1)  %>
    <i class="fas fa-star"></i>
  <% else %>
    <i class="far fa-star"></i>
  <% end  %>
<% end  %>
  

app/views/shelter_reviews/new.html.erb
<div class="container mt-5">
  <div class="row border border-warning justify-content-center p-5">
  <div class="col-6">
    <h2 style="text-align:center">Please leave a review </h2>
    <%= simple_form_for [@reservation, @shelter_review] do |f| %>
      
      <%= f.input :rating %>
      <%= f.input :content %>
      <%= f.submit "Submit review", class: "btn btn-info rounded-pill " %>
    <% end %>
  </div>

</div>

app/views/shelters/new.html.erb
<%= simple_form_for @shelter do |f| %>
<%= f.input :name  %>
<%= f.submit %>
<% end %>

app/views/shelters/show.html.erb
<div class=" mb-4 mt-4 mx-auto" style="width: 700px;">
<h1 class="text-center"><%= @shelter.name  %> 🏡</h1>

  <h4 class = "text-center mr-3 mb-4"><%= @shelter.user.address%>, <%= @shelter.user.city%> <%= @shelter.user.zip_code%> </h4>
  <% if current_user.present? && current_user.shelter == @shelter %>
    <%= link_to "Add New Pet", new_shelter_pet_path(@shelter), class: "btn btn-primary add-btn mx-auto" %>
  <% end %>
</div>
<div class="container1 text-center">
  <div class="row main-holder">
    <% @pets.each do |pet| %>
    <div class="col-sm-5 mx-auto" style="margin-bottom: 35px;">
      <div class="card individual-card justify-content-around show-card" style="height: 620px;">
        <% pet_photo_key = get_photo_key(pet) %>
        
        <div>
          <%= cl_image_tag pet_photo_key, alt: "pet photo", class: "show-img card-img-top" %>
        </div>

        <div class="card-body list-group list-group-flush d-flex flex-column align-items-center ">
          <div class="card-title">
            <%= pet.name %>
          </div>
          <div class="card-text">
            <%= pet.description %>
          </div>
          <div class="list-group-item">Age:
            <%= pet.age %>
          </div>
          <div class="list-group-item">
            Gender: <%= pet.gender %>
          </div>
          <div class="list-group-item">
           Breed: <%= pet.breed %>
          </div>
          <div class="list-group-item">
            Shelter: <%= link_to pet.shelter.name, shelter_path(pet.shelter) %>
          </div>
          <div class="list-group-item">
            Location: <%= pet.shelter.user.city %>
          </div>
          <div class="list-group-item">
            Price per day: <%= pet.price_per_day %>
          </div>
            <% if current_user.present? && current_user.shelter == @shelter %>
            <div class="bottom-link1">
            <%= link_to "Edit information of #{pet.name}" , edit_pet_path(pet), class: "bottom-link" %>
            </div>
          <% else %>
          <div class="bottom-link1">
            <%= link_to "Learn more about #{pet.name}", pet_path(pet), class: "bottom-link" %>
            </div>
          <% end %>
      </div>
      </div>

    </div>
    <% end %>
  </div>
</div>